basket = ['apple', 'banana', 'orange', 'strawberry', 'grape'] 
basket.remove('banana')
print(basket)
basket.remove('grape')
print(basket)
basket.append('kiwi')
print(basket)   
basket.append('melon')
print(basket)   
print(basket.count('apple'))
basket.remove('apple')
basket.remove('orange')
basket.remove('strawberry')
basket.remove('kiwi')
basket.remove('melon')
print(basket)
